<?php
/**
 * Fabbriche Aperte Piemonte functions
 *
 */

add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );

function my_theme_enqueue_styles() {
	wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
	wp_enqueue_style( 'child-style',
		get_stylesheet_directory_uri() . '/style.css',
		array( 'parent-style' ),
		wp_get_theme()->get('Version') );
}

add_image_size( 'twentyseventeen-thumbnail-fabbrica', 300, 300, true );

function fap_content_width() {

	$content_width = $GLOBALS['content_width'];

	// Get layout.
	$page_layout = get_theme_mod( 'page_layout' );

	// Check if layout is one column.
	if ( 'one-column' === $page_layout ) {
		if ( twentyseventeen_is_frontpage() ) {
			$content_width = 644;
		} elseif ( is_page() ) {
			$content_width = 1000;
		}
	}

	// Check if is single post and there is no sidebar.
	if ( is_single() && ! is_active_sidebar( 'sidebar-1' ) ) {
		$content_width = 1000;
	}

	/**
	 * Filter Twenty Seventeen content width of the theme.
	 *
	 * @since Twenty Seventeen 1.0
	 *
	 * @param $content_width integer
	 */
	$GLOBALS['content_width'] = apply_filters( 'twentyseventeen_content_width', $content_width );
}
remove_action( 'template_redirect', 'twentyseventeen_content_width', 0 );
add_action( 'template_redirect', 'fap_content_width', 0 );

unregister_sidebar( 'sidebar-1' );

wp_dequeue_style( 'twentyseventeen-fonts' );

function fap_content_image_sizes_attr( $sizes, $size ) {
	$width = $size[0];

	if ( 1000 <= $width ) {
		$sizes = '(max-width: 706px) 89vw, (max-width: 767px) 82vw, 1000px';
	}

	if ( is_active_sidebar( 'sidebar-1' ) || is_archive() || is_search() || is_home() || is_page() ) {
		if ( ! ( is_page() && 'one-column' === get_theme_mod( 'page_options' ) ) && 767 <= $width ) {
			 $sizes = '(max-width: 767px) 89vw, (max-width: 1000px) 54vw, (max-width: 1071px) 543px, 580px';
		}
	}

	return $sizes;
}
remove_filter( 'wp_calculate_image_sizes', 'twentyseventeen_content_image_sizes_attr', 10 );
add_filter( 'wp_calculate_image_sizes', 'fap_content_image_sizes_attr', 10, 2 );

add_action( 'init', 'fap_crea_fabbriche' );
function fap_crea_fabbriche() {
	register_post_type( 'fabbriche',
	array(
		'labels' => array(
			'name' => __( 'Fabbriche' ),
			'singular_name' => __( 'Fabbrica' )
		),
		'public' => true,
		'has_archive' => true,
		'rewrite' => array('slug' => 'fabbriche'),
		'supports' => array('title', 'editor', 'thumbnail', 'excerpt', 'page-attributes'),
		)
	);
}

function fap_add_fabbriche_body_class( $classes ) {
	global $post;
	if ( isset( $post ) && $post->post_type == 'fabbriche' && !is_archive() ) {
		$classes[] = 'has-sidebar';
	}
	return $classes;
}
add_filter( 'body_class', 'fap_add_fabbriche_body_class' );

function fap_remove_menus(){
	remove_menu_page( 'edit.php' );          //Posts
	remove_menu_page( 'edit-comments.php' ); //Comments
}
add_action( 'admin_menu', 'fap_remove_menus' );

function fap_building_info() {
	$custom_fields = get_field_objects();
	$building_info = ['apertura_venerdi', 'apertura_sabato', 'persone_visita', 'durata_visita',
		'identificazione_partecipanti', 'antinfortunistica', 'richieste_particolari', 'accessibilità', 'prenotazioni',
		'sito_web', 'facebook', 'twitter', 'instagram', 'indirizzo', 'mezzi_pubblici', 'parcheggio_privato' ];
	$output = '<ul>';
	$address = str_replace( ', Italy', '', $custom_fields['indirizzo']['value']['address'] );
	foreach ($building_info as $info) {
		if ( array_key_exists($info, $custom_fields) && !empty($custom_fields[$info]['value']) ) {
			$value = $custom_fields[$info]['value'];
			if ( $info != 'indirizzo' && strpos( $value, 'http' ) !== false ) {
				$value = str_replace( 'http://www.', '', $value );
				$value = str_replace( 'https://www.', '', $value );
				$value = '<a href="'.$value.'" target="_blank">'.$value.'</a>';
			}
			if ( $info == 'indirizzo' ) {
				$value = '<a href="https://www.google.it/maps?q='.$address.'" target="_blank">'.$address.'</a>';
			}
			$output .= '<li><b>'.$custom_fields[$info]['label'].':</b> '.$value.'</li>';
		}
	}
	$output .= '</ul>';
	$lat = $custom_fields['indirizzo']['value']['lat'];
	$lng = $custom_fields['indirizzo']['value']['lng'];
	$output .= '<a href="https://www.google.it/maps?q='.$address.'" target="_blank">'.
	'<img src="https://maps.googleapis.com/maps/api/staticmap?center='.$lat.','.$lng.
	'&zoom=15&size=300x300&maptype=roadmap&markers=color:red%7C'.$lat.','.$lng.
	'&key=AIzaSyChbI5EcduTRA7PcNjZzE_BWOP5b3ikwVo" /></a>';
	return $output;
}

function my_acf_google_map_api( $api ){
	$api['key'] = 'AIzaSyBNjXHb9FNrUR_WOC0gHprUEEbHvd_aKIY';
	return $api;
}
add_filter('acf/fields/google_map/api', 'my_acf_google_map_api');

// Generated by Advanced custom fields
include_once('advanced-custom-fields/acf.php');
define( 'ACF_LITE', true );

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_info-fabbrica',
		'title' => 'Info fabbrica',
		'fields' => array (
			array (
				'key' => 'field_59c5117229ad6',
				'label' => 'Apertura venerdì',
				'name' => 'apertura_venerdi',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c514d9fa419',
				'label' => 'Apertura sabato',
				'name' => 'apertura_sabato',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c514eefa41a',
				'label' => 'Persone / visita',
				'name' => 'persone_visita',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51505fa41b',
				'label' => 'Durata visita',
				'name' => 'durata_visita',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51513fa41c',
				'label' => 'Indirizzo',
				'name' => 'indirizzo',
				'type' => 'google_map',
				'center_lat' => '45.0716336',
				'center_lng' => '7.6906471',
				'zoom' => 9,
				'height' => '',
			),
			array (
				'key' => 'field_59c51546fa41d',
				'label' => 'Mezzi pubblici',
				'name' => 'mezzi_pubblici',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51550fa41e',
				'label' => 'Parcheggio privato',
				'name' => 'parcheggio_privato',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51561fa41f',
				'label' => 'Identificazione partecipanti',
				'name' => 'identificazione_partecipanti',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51570fa420',
				'label' => 'Antinfortunistica',
				'name' => 'antinfortunistica',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c5157dfa421',
				'label' => 'Richieste particolari',
				'name' => 'richieste_particolari',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51588fa422',
				'label' => 'Accessibilità',
				'name' => 'accessibilità',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51593fa423',
				'label' => 'Prenotazioni',
				'name' => 'prenotazioni',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51593fa424',
				'label' => 'Sito web',
				'name' => 'sito_web',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51593fa425',
				'label' => 'Facebook',
				'name' => 'facebook',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51593fa426',
				'label' => 'Twitter',
				'name' => 'twitter',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_59c51593fa427',
				'label' => 'Instagram',
				'name' => 'instagram',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'fabbriche',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_provincia',
		'title' => 'Provincia',
		'fields' => array (
			array (
				'key' => 'field_59c5168825d53',
				'label' => 'Provincia',
				'name' => 'provincia',
				'type' => 'radio',
				'choices' => array (
					'Alessandria' => 'Alessandria',
					'Asti' => 'Asti',
					'Biella' => 'Biella',
					'Cuneo' => 'Cuneo',
					'Novara' => 'Novara',
					'Torino' => 'Torino',
					'Verbania Cusio Ossola' => 'Verbania Cusio Ossola',
					'Vercelli' => 'Vercelli',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'Torino',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'fabbriche',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'categories',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_categoria',
		'title' => 'Categoria',
		'fields' => array (
			array (
				'key' => 'field_59c517c86992c',
				'label' => 'Categoria',
				'name' => 'categoria',
				'type' => 'checkbox',
				'choices' => array (
					'Aerospace' => 'Aerospazio',
					'Agroalimentare' => 'Agroalimentare',
					'Automotive' => 'Automotive',
					'Chimica' => 'Chimica, farmaceutica, biomedicina',
					'Design' => 'Design e manifattura',
					'Editoria' => 'Editoria',
					'Elettronica' => 'Elettronica',
					'Ferroviario' => 'Ferroviario',
					'ICT' => 'ICT',
					'Materie plastiche e fabbricazione pneumatici' => 'Materie plastiche e fabbricazione pneumatici',
					'Meccanica' => 'Metalmeccanica, meccanica e automazione industriale',
					'Servizi' => 'Servizi avanzati',
					'Tessile' => 'Tessile',
				),
				'default_value' => '',
				'layout' => 'vertical',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'fabbriche',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 10,
	));
}
// END - Generated by Advanced custom fields